bf16: true
cutoff_len: 32768
dataset: medqa
dataset_dir: data
ddp_timeout: 180000000
do_train: true
finetuning_type: full
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 1.0e-05
logging_steps: 1
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1000000
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
num_train_epochs: 5.0
optim: adamw_torch
output_dir: saves/Qwen2.5-7B-Instruct
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 10000
stage: sft
template: qwen
trust_remote_code: true
warmup_steps: 0
